version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: Akka.Persistence.Sql.TestKit
    versions:
    - 1.4.17
  - dependency-name: Akka.Persistence.Sql.Common
    versions:
    - 1.4.17
